version: 2
jobs:
  build:
    docker:
      - image: gcc:latest

    steps:
      - checkout

      - run:
          name: checkout bullet
          command: ./git-bullet.sh

      - run:
          name: make
          command: make
