#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            100
#define IDD_MAINDLG                             129
#define IDD_PREVIEW                             201
#define IDC_MOVEDELTA                           1000
#define IDC_EDITROTDELTA                        1001
#define IDC_PREVIEW                             1002
#define IDC_BONELIST                            1003
#define IDC_OPENMODEL                           1004
#define IDC_OPENMOTION                          1005
#define IDC_SAVEMOTION                          1006
#define IDC_MOTIONLIST                          1007
#define IDC_TIMESLIDER                          1008
#define IDC_KEYFRAMELIST                        1009
#define IDC_CURRENTFRAME                        1010
#define IDC_POSELIST                            1011
#define IDC_DELETEBONEPOSE                      1012
#define IDC_ADDBONEPOSE                         1013
#define IDC_RXP                                 1014
#define IDC_RXN                                 1015
#define IDC_RYP                                 1016
#define IDC_RYN                                 1017
#define IDC_RZP                                 1018
#define IDC_RZN                                 1019
#define IDC_MXP                                 1020
#define IDC_MXN                                 1021
#define IDC_MYP                                 1022
#define IDC_MYN                                 1023
#define IDC_MZP                                 1024
#define IDC_MZN                                 1025
#define IDC_ADDKEYFRAME                         1026
#define IDC_COMBINEDPOSE                        1027
#define IDC_INSERTKEYFRAME                      1028
#define IDC_KEYFRAMETIME                        1029
#define IDC_COPYKEYFRAME                        1030
#define IDC_PASTEKEYFRAME                       1031
#define IDC_VISIBILITY                          1032
#define IDC_SAVEMOTION2                         1033
#define IDC_AMPLITUDE                           1034
#define IDR_MAINFRAME                           40000
