/** \file
 * \brief Definition of Mesh and MeshTex classes.
 */
#ifndef MESH_H
#define MESH_H
#include "Mesh-forward.h"
#include "export.h"
#include <limits.h>
#ifdef _WIN32
#include <windows.h>
#endif
#include <GL/GL.h>

#define EXTENDABLE 1

/* DrawSUF flags */
#define SUF_ATR 0xff /* enable attribute-file specified material if one exists */
#define SUF_COL (1<<0) /* validity flags */
#define SUF_TRA (1<<1)
#define SUF_AMB (1<<2)
#define SUF_DIF (1<<3)
#define SUF_SPC (1<<4)
#define SUF_TEX (1<<5) /* texture presence */
#define SUF_EMI (1<<6) /* emissivity, not generated by standard PolyEdit */
#define SUF_MTX (1<<7) /* multi-texture presence */
#define SUF_VA  (1<<8) /* use vertex array to draw polygons */

/// \brief A mesh of polygon surfaces.
///
/// This class is designed to be as much compatible as possible to clib's suf_t,
/// but defined in C++ for better integration to the application.
///
/// Keep it a POD (Plain Old Data) or the compatibility may be broken.
/// This also applies to all sub-structs.
struct EXPORT Mesh{
	typedef double Coord; ///< Internal coordinate value type
	typedef unsigned short Index; ///< Internal index value for attributes and vertex buffers.
	typedef Coord Vec[3]; ///< Internal vector class in 3-D.

	static const Index INDEX_MAX = USHRT_MAX; ///< Maximum value of an Index variable.

	int nv;
	Vec *v;

	/// \brief Attribute parameters compatible to sufatr_t.
	struct Attrib{
		char *name;
		unsigned valid; /* validity flag of following values */
		float col[4]; /* clamped */
		float tra[4];
		float amb[4]; /* ambient */
		float emi[4]; /* emission */
		float dif[4]; /* diffuse */
		float spc[4]; /* specular lighting */
		char *colormap; /* texture color map name */
		Coord mapsize[4];
		Coord mapview[4];
		Coord mapwind[4];
	};

	Index na;
	Attrib *a;

	/// \brief Type of primitive.
	enum ElemType{suf_poly, suf_shade, suf_uvpoly, suf_uvshade};

	/// \brief Polygon primitive.
	struct Polygon{
		ElemType t;
		int n;
		Index atr; /* index into attribute list */
		Index v[EXTENDABLE][2]; /* index into vertex list, position and normal */
	};

	/// \brief UV-mapped polygon primitive.
	struct UVPolygon{
		ElemType t;
		int n;
		Index atr;
		struct suf_uvpoly_vertex{
			Index p, n, t; /* position, normal and texture coordinates. */
		} v[1];
	};

	/// \brief Union of all possible primitives.
	union Primitive{
		ElemType t;
		Polygon p;
		UVPolygon uv;
	};

	int np;
	Primitive **p;

	/// \brief Attribute cache that could be used to optimize performance (though somewhat unstable).
	struct Cache{
		unsigned long valid;
		float matdif[4];
		float matamb[4];
		float matemi[4];
		float matspc[4];
		GLuint texture;
		int texenabled;
	};

	/// \brief Deprecated decal data, provided only for compatibility for the time being.
	struct Decal{
		void (*drawproc)(void*, Cache *, void *global_var);
		void (*freeproc)(void*);
		int np;
		void *p[1];
	};

	~Mesh();

	Attrib *find_atr(const char *name);
	void draw(unsigned long flags, Cache *)const;
	static void gldMaterialfv(GLenum face, GLenum pname, const GLfloat *params, Cache *c);
	void polyDraw(unsigned long flags, Cache *c, int i, Index *plast, const MeshTex *)const;
	void drawPoly(int i, unsigned long flags, Cache *c)const;
	void decalDraw(unsigned long flags, Cache *c, const MeshTex *tex, Decal *sd, void *sdg)const;
	Index Mesh::add_vertex(const Vec &v);
	Primitive **add_poly();
	static void add_polyvert(Polygon **p, Index i, Index j);
	static void add_uvpolyvert(UVPolygon **uv, Index i, Index j, Index k);
};

/// \brief A texture cache used for drawing a Mesh.
///
/// This class is similar to suftex_t.
///
/// Keep it a POD (Plain Old Data) or the compatibility may be broken.
struct EXPORT MeshTex{
	/// A internal structure to store texture unit and its initialization methods.
	struct MeshTexList{
		GLuint list; ///< OpenGL list executed when the beginning of texture
		GLuint tex[2]; ///< Texture names for each multitexture
		double scale; ///< Scale of the second texture (for detail texturing)
		void (*onBeginTexture)(void *data); ///< Called just before the texture is activated
		void *onBeginTextureData; ///< Argument for onBeginTexture
		void (*onInitedTexture)(void *data); ///< Called just after the texture is initialized
		void *onInitedTextureData; ///< Argument for onInitedTexture
		void (*onEndTexture)(void *data); ///< Called when the texture unit is ended.
		void *onEndTextureData; ///< Argument for onEndTexture
	};

	unsigned n;
	struct MeshTexList a[1];
};


#endif
